inherit_from: .rubocop_todo.yml
require: rubocop-rspec

Style/Documentation:
  Exclude:
    - '**/*.rb'

RSpec/InstanceVariable:
  Exclude:
    - 'spec/views/**/*.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/**/*.rb'

Lint/ScriptPermission:
  Exclude:
    - 'bin/**/*'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'db/schema.rb'

Layout/EndOfLine:
  EnforcedStyle: lf

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.*'

